export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const GET_CAT_PRODUCT_REQUEST = "GET_CAT_PRODUCT_REQUEST";
export const GET_CAT_PRODUCT_SUCCESS = "GET_CAT_PRODUCT_SUCCESS";
export const GET_CAT_PRODUCT_FAIL = "GET_CAT_PRODUCT_FAIL";
