export const GET_DELIVERY_REQUEST = "GET_DELIVERY_REQUEST";
export const GET_DELIVERY_SUCCESS = "GET_DELIVERY_SUCCESS";
export const GET_DELIVERY_FAIL = "GET_DELIVERY_FAIL";
export const GET_DELIVERY_RESET = "GET_DELIVERY_RESET";
